[build-system]
requires = [
    "wheel",
    "setuptools",
    "cython>=0.28.0,<=0.29.36", # Cython 3.0.0 causes #95
    "numpy>=v1.20.0",
    "scipy",
]


[tool.pysen]
version = "0.10.2"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = false
mypy_preset = "entry"
line_length = 88
py_version = "py37"

[[tool.pysen.lint.mypy_targets]]
paths = ["pysptk", "tests"]
